### ISSUE TITLE
Não exibição das imagens no Mobile

### ISSUE THREAD

**Issue by LeuAlmeida** [Rocketseat/semana-omnistack-9#4]
Boa noite,

Preciso de uma ajuda da galera que entende mais que eu de React Native rsss.
Com o meu projeto parado na aula 4 da Semana 9, eu travei com a minha aplicação bugada em relação a puxar a thumbnail.

![image](https://user-images.githubusercontent.com/42948574/66357133-1c199f80-e944-11e9-8010-5584f40cc788.png)

Repositório: https://github.com/LeuAlmeida/aircnc

Alguém sabe pq rolou isso?

**Comment by jpedroschmitz** [comment]
Fala @LeuAlmeida, dá uma olhada [nesse repositório](https://github.com/Rocketseat/expo-common-issues#imagens-n%C3%A3o-aparecendo-no-dispositivo-f%C3%ADsico) que criamos para vocês. Se não resolver o seu problema recomendo trocar uma ideia com a galera na nossa [comunidade](https://rocketseat.com.br/comunidade).
