### ISSUE TITLE
 imagem nao mostra no dispositvo

### ISSUE THREAD

**Issue by hilquiasfmelo** [Rocketseat/semana-omnistack-9#8]
Pessoal ate alterei o ip no backend mais nao aparece a imagem dos spots no dispostivo mobile

**Comment by Wennlys** [comment]
Cara, estou tendo o EXATO mesmo problema. Conseguiu resolver? Eu tava achando que era algum problema no meu backend.

**Comment by lucaspontoexe** [comment]
Entra no código do [model do spot](https://github.com/Rocketseat/semana-omnistack-9/blob/master/backend/src/models/Spot.js) e troca `localhost` pelo IP do seu computador.

**Comment by lucaspontoexe** [comment]
> ate alterei o ip no backend
momento "falta de atenção"

olha o arquivo List.js do mobile e vê se está com o IP certo
https://github.com/Rocketseat/semana-omnistack-9/blob/master/mobile/src/pages/List.js

**Comment by lucaspontoexe** [comment]
mesma coisa na [configuração da api](https://github.com/Rocketseat/semana-omnistack-9/blob/master/mobile/src/services/api.js)

**Comment by jpedroschmitz** [comment]
Fala @LeuAlmeida, dá uma tópico [do repositório](https://github.com/Rocketseat/expo-common-issues#imagens-n%C3%A3o-aparecendo-no-dispositivo-f%C3%ADsico) que criamos para vocês. Se não resolver o seu problema recomendo trocar uma ideia com a galera na nossa [comunidade](https://rocketseat.com.br/comunidade).

**Comment by LeuAlmeida** [comment]
Acredito que vc me mencionou por engano @jpedroschmitz . De qualquer forma, dá uma lida na resposta dele @lucaspontoexe

**Comment by jpedroschmitz** [comment]
Haha, desculpa pelo engano. Copiei a mensagem da outra issue.

**Comment by LeuAlmeida** [comment]
Sem problemas, fica tranquilo!
